# Generated by Django 4.2.7 on 2023-12-06 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacreisaude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
