# Generated by Django 4.2.7 on 2023-12-06 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lacreisaude', '0002_consulta_data_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
